version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "save_hello_world_output"
          command: "echo hello_world > output.txt && pwd "
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      #- checkout
      - attach_workspace:
            at: /home/circleci/project
      - run:
          name: "print data persistent in a text file"
          command: "cat  output.txt"
workflows:
  perisit _files:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output